const events=[
 {id:'sst',type:'test',date:'28 SEP',subject:'SST',title:'SST Test',topic:'Chapter 1 Q&A',when:'Tomorrow',status:'Tomorrow',urgent:true},
 {id:'science',type:'submission',date:'29 SEP',subject:'Science',title:'Science Notebook',topic:'Chapter 1–4 Notebook',when:'2 days',status:'2 days',urgent:false},
 {id:'maths',type:'test',date:'02 OCT',subject:'Maths',title:'Maths Test',topic:'Ex 7.1–7.3',when:'5 days',status:'5 days',urgent:false},
 {id:'english',type:'assignment',date:'04 OCT',subject:'English',title:'Writing assignment',topic:'A letter to my future self',when:'7 days',status:'7 days',urgent:false}
];
const state={page:localStorage.getItem('cp_onboard')?'home':'onboarding',dark:localStorage.getItem('cp_theme')==='dark',name:localStorage.getItem('cp_name')||'',className:'8',section:'A',tone:'Funny',alerts:true,filter:'upcoming'};
document.body.classList.toggle('dark',state.dark);
function save(){localStorage.setItem('cp_name',state.name);localStorage.setItem('cp_onboard','1');localStorage.setItem('cp_theme',state.dark?'dark':'light')}
function app(){document.getElementById('app').innerHTML=state.page==='onboarding'?onboarding():shell();}
function onboarding(){return `<main class="onboarding"><div class="topbar"><div class="brand"><span class="brand-mark">⌁</span>ClassPing</div><button class="ghost" onclick="toggleTheme()">${state.dark?'☀ Light':'◐ Dark'}</button></div><section class="card"><div><div class="eyebrow">${stepLabel()}</div><div class="progress"><i style="width:${(onboarding.step||1)*25}%"></i></div></div><div class="step">${stepMarkup()}</div><button class="button" onclick="nextStep()">${(onboarding.step||1)===4?'Enable reminders':'Continue'}</button></section></main>`}
onboarding.step=1;
function stepLabel(){return ['Welcome','Your name','Your class','Choose your vibe'][onboarding.step-1]}
function stepMarkup(){if(onboarding.step===1)return `<h1>Know it before<br>you miss it.</h1><p class="subhead">Tests, submissions and school reminders — automatically organized for you.</p>`;if(onboarding.step===2)return `<h2>What should we call you?</h2><p class="subhead">This name will appear in your reminders.</p><div class="field"><label>Your name</label><input id="name" placeholder="Kanish" value="${state.name}"></div>`;if(onboarding.step===3)return `<h2>Your class</h2><p class="subhead">Set this once. You can change it later.</p><div class="field"><label>Class</label><input id="className" value="${state.className}"></div><div class="field"><label>Section</label><input id="section" value="${state.section}"></div>`;return `<h2>Choose your vibe</h2><p class="subhead">Pick the look that feels right for you.</p><div class="choice-grid"><button class="choice ${!state.dark?'selected':''}" onclick="setTheme(false)">☀<br>Light</button><button class="choice ${state.dark?'selected':''}" onclick="setTheme(true)">◐<br>Dark</button></div>`}
function nextStep(){if(onboarding.step===2)state.name=document.getElementById('name').value||'Student';if(onboarding.step===3){state.className=document.getElementById('className').value||'8';state.section=document.getElementById('section').value||'A'}if(onboarding.step===4){save();state.page='home';onboarding.step=1;app();return}onboarding.step++;app()}
function shell(){return `<main class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">⌁</span>ClassPing</div><div><button class="ghost" onclick="toggleTheme()">${state.dark?'☀':'◐'}</button><button class="ghost" onclick="go('settings')">⚙</button></div></header>${content()}${nav()}</main>`}
function nav(){return `<nav class="nav">${[['home','⌂','Home'],['tests','▦','Tests'],['submissions','▤','Submissions'],['settings','⚙','Settings']].map(x=>`<button class="${state.page===x[0]?'active':''}" onclick="go('${x[0]}')">${x[1]} ${x[2]}</button>`).join('')}</nav>`}
function content(){if(state.page==='tests')return listing('Tests',events.filter(e=>e.type==='test'));if(state.page==='submissions')return listing('Submissions',events.filter(e=>e.type==='submission'));if(state.page==='settings')return settings();if(state.page==='detail')return detail();return home()}
function home(){let next=events[0];return `<section class="grid"><div class="hero card"><div><div class="eyebrow">Good afternoon, ${state.name||'Kanish'}</div><p class="subhead">Here’s what you need to know.</p></div><div class="next"><div><div class="eyebrow">Next up</div><h2>${next.title}</h2><p class="subhead">${next.topic}</p></div><div class="countdown">${next.when}<br><small>${next.subject}</small></div></div></div><div class="card"><div class="eyebrow">This week</div><div class="stats" style="margin-top:28px"><div class="stat"><strong>3</strong><span>Tests</span></div><div class="stat"><strong>2</strong><span>Submissions</span></div><div class="stat"><strong>1</strong><span>Assignment</span></div></div></div></section><div class="section-head"><h2>Upcoming</h2><button class="button secondary" onclick="go('tests')">View tests</button></div><div class="event-list">${events.map(eventRow).join('')}</div>`}
function listing(title,list){let visible=state.filter==='past'?[]:list;return `<section><div class="eyebrow">ClassPing schedule</div><h1>${title}</h1><p class="subhead">Stay a step ahead of what’s next.</p><div class="filters"><button class="filter ${state.filter==='upcoming'?'active':''}" onclick="setFilter('upcoming')">Upcoming</button><button class="filter ${state.filter==='past'?'active':''}" onclick="setFilter('past')">Past</button></div>${visible.length?`<div class="table"><div class="table-row table-head"><span>Date</span><span>Subject</span><span>Syllabus / what to submit</span><span>Status</span></div>${visible.map(e=>`<div class="table-row" onclick="openDetail('${e.id}')"><strong>${e.date}</strong><strong>${e.subject}</strong><span>${e.topic}</span><span class="pill ${e.urgent?'urgent':''}">${e.status}</span></div>`).join('')}</div>`:`<div class="card empty">No ${title.toLowerCase()} coming up 🎉<br>Enjoy the peace while it lasts.</div>`}</section>`}
function eventRow(e){return `<div class="event" onclick="openDetail('${e.id}')"><div class="event-date">${e.date}<br><small>${e.when}</small></div><div class="event-main"><strong>${e.title}</strong><span>${e.subject} · ${e.topic}</span></div><span class="pill ${e.urgent?'urgent':''}">${e.type==='test'?'Test':e.type==='submission'?'Submit':'Plan'}</span></div>`}
function detail(){let e=events.find(x=>x.id===state.detail)||events[0];return `<section class="detail"><button class="ghost" onclick="go('home')">← Back</button><div class="card" style="margin-top:18px"><div class="eyebrow">${e.type==='test'?'Test':'Submission'}</div><h1>${e.title}</h1><p class="subhead">${e.subject}</p><div class="detail-meta"><div class="meta"><small>When</small><strong>${e.date} · ${e.when}</strong></div><div class="meta"><small>Reminder</small><strong>24 hours before</strong></div><div class="meta"><small>${e.type==='test'?'Syllabus':'What to submit'}</small><strong>${e.topic}</strong></div><div class="meta"><small>Source</small><strong>School</strong></div></div><button class="button secondary" onclick="go('home')">Done</button></div></section>`}
function settings(){return `<section class="settings"><div class="eyebrow">Your ClassPing</div><h1>Settings</h1><p class="subhead">Tune reminders and make it feel like yours.</p><div class="card"><div class="field"><label>Name</label><input value="${state.name||'Kanish'}" onchange="state.name=this.value;save()"></div><div class="field"><label>Class</label><input value="${state.className}" onchange="state.className=this.value"></div><div class="field"><label>Section</label><input value="${state.section}" onchange="state.section=this.value"></div><div class="setting"><div><strong>Master notifications</strong><p>Remind me before school events</p></div><button class="switch ${state.alerts?'on':''}" onclick="state.alerts=!state.alerts;app()"><i></i></button></div><div class="setting"><div><strong>Theme</strong><p>${state.dark?'Dark':'Light'} mode</p></div><button class="button secondary" onclick="toggleTheme()">Change</button></div><div class="setting"><div><strong>Reminder timing</strong><p>24 hours before each event</p></div><span class="pill">24 hours</span></div><div class="setting"><div><strong>Notification style</strong><p>Choose your tone</p></div><select onchange="state.tone=this.value"><option>Funny</option><option>Normal</option><option>Simple</option></select></div></div><p class="muted" style="margin-top:22px">ClassPing 1.0.0 · Know it before you miss it.</p></section>`}
function go(p){state.page=p;app()}function openDetail(id){state.detail=id;state.page='detail';app()}function setFilter(f){state.filter=f;app()}function setTheme(dark){state.dark=dark;document.body.classList.toggle('dark',dark);app()}function toggleTheme(){state.dark=!state.dark;document.body.classList.toggle('dark',state.dark);save();app()}app();
